# Generated by Django 3.0.3 on 2020-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_location', models.CharField(max_length=50)),
            ],
        ),
    ]
