# Generated by Django 3.0.3 on 2020-04-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0003_auto_20200410_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_bestSeller',
            field=models.CharField(default=None, max_length=30, verbose_name='Product Best Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(verbose_name='Product Price (in LL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_qty',
            field=models.IntegerField(verbose_name='Product Quantity'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(verbose_name='Data of supply')),
                ('supply_qty', models.IntegerField(verbose_name='Quantity supplied')),
                ('supply_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Product', verbose_name='Product ID')),
                ('supply_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Supplier', verbose_name='Supplier ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='members',
            field=models.ManyToManyField(through='MunchBox.Supply', to='MunchBox.Supplier'),
        ),
    ]
