# Generated by Django 3.0.3 on 2020-04-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0004_auto_20200410_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='supply_product',
            new_name='supply_productID',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='supply_supplier',
            new_name='supply_supplierID',
        ),
    ]
