# Generated by Django 3.0.3 on 2020-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0005_auto_20200410_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supply_cost',
            field=models.IntegerField(default=0, verbose_name='Cost of 1 item'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_date',
            field=models.DateField(verbose_name='Date of supply'),
        ),
    ]
