# Generated by Django 3.0.3 on 2020-04-10 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0006_auto_20200410_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_bestSeller',
            field=models.CharField(default='Unknown Yet', max_length=30, verbose_name='Product Best Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_qty',
            field=models.IntegerField(default=0, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cost of 1 item'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
    ]
