# Generated by Django 3.0.3 on 2020-04-10 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0007_auto_20200410_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_totalPrice', models.IntegerField(default=0, verbose_name='Total Price')),
                ('order_deliveryFee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery Fee')),
            ],
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cost of 1 item (in LL)'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(verbose_name='Date and time of order')),
                ('request_profit', models.DateTimeField(verbose_name='Profit')),
                ('request_OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Order', verbose_name='Order ID')),
                ('request_customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Customer', verbose_name='Customer ID')),
                ('request_productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Product', verbose_name='Product ID')),
            ],
        ),
    ]
