# Generated by Django 3.0.3 on 2020-04-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0008_auto_20200410_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_OrderID',
            new_name='request_orderID',
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('request_customerID', 'request_productID', 'request_orderID')},
        ),
    ]
