# Generated by Django 3.0.3 on 2020-04-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0009_auto_20200411_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_profit',
            field=models.IntegerField(default=0, verbose_name='Profit'),
        ),
    ]
