# Generated by Django 3.0.3 on 2020-04-10 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0010_auto_20200411_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MunchBox.Customer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_deliveryFee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery Fee'),
        ),
    ]
