# Generated by Django 3.0.3 on 2020-04-11 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MunchBox', '0013_auto_20200411_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_deliveryFee',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_productQty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Requested'),
        ),
    ]
